/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillpaymentComponent: typeof import('./src/components/firstSection/components/BillpaymentComponent.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Insight: typeof import('./src/components/insight.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Loans: typeof import('./src/components/loans.vue')['default']
    NairaIcon: typeof import('./src/components/icons/NairaIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/ui/spinner/Spinner.vue')['default']
    SunsetSvg: typeof import('./src/components/sunsetSvg.vue')['default']
    Transaction: typeof import('./src/components/Transaction.vue')['default']
  }
}
